### PR TITLE
Support platform specific dependencies

### PR DESCRIPTION
**Pull request by wildarch**
Add `select({})`s to deps attributes that select dependencies based on the rules_rust target platform matched. This allows generating a single `cargo_dependencies.bzl` file that can be used for any target triple.

For now we only support 64-bit Linux and Mac. Other targets should work too, but we cannot test them with the currrent CI setup.

Builds on https://github.com/SirWindfield/blackjack/pull/1 to retrieve the correct `cargo` executable on all platforms and pass the cargo executable and manifest paths in `args`.

I would like to add support for windows too (and got pretty far into supporting that), but ran into some issues with `winapi`, which is hard for me to debug without access to a Windows machine outside of CI.

### CODE REVIEW

**Comment by wildarch** [comment]
@SirWindfield this approach seems to work quite well, do you think it covers your needs for #5?

**Comment by SirWindfield** [comment]
Looks good! What problems did you encounter when trying to add Windows?

**Comment by wildarch** [comment]
> Looks good! What problems did you encounter when trying to add Windows?

The winapi crate was giving me some issues. I think it's just about enabling the right flag (looks like normally the build script takes care of that), but without an interactive windows environment to test I couldn't get things to build. If someone has access to a Windows machine and can get this sorted, that would be awesome 😊

**Comment by SirWindfield** [comment]
https://github.com/google/cargo-raze/issues/41 contains a good amount of code related to special crates. Might come handy :)

**Pull request merged**
